GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
    
}


###
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
    "name": "Notebook Lenovo",
    "price": 5423
}

###
DELETE http://localhost:3000/products/2