GET http://localhost:3000/products

###
GET http://localhost:3000/products/45

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Produto 2",
    "price": 654
}


###
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
    "price": 700
}

###
DELETE http://localhost:3000/products/2